### ISSUE TITLE
Publish to aquila.red

### ISSUE THREAD

**Issue by demizer** [getty-zig/getty#23]
https://aquilla.red is a package index for zigmod

This would make it simple to add this package to a project via zigmod:

```
zigmod aq add 1/getty-zig/getty
zigmod fetch
```

**Comment by ibokuri** [comment]
Sounds good to me! Would you like to take a crack at it? I believe it's just:

1. `zigmod init`
2. Update installation section in README.
3. Update CI file to install Zigmod as a dependency.
4. Publish to Aquila (which I'll do after the PR's merged).

**Comment by demizer** [comment]
Will do!

**Comment by demizer** [comment]
This will have to be put on the backburner until zigmod supports publishing from github organizations (https://github.com/nektro/zigmod/issues/63#issuecomment-1063205053)

**Comment by nektro** [comment]
being published on the site is not a requirement of having a `zigmod.yml` manifest

**Comment by ibokuri** [comment]
@demizer We can make publishing to Aquila a separate issue then, and change this one to just adding support for Zigmod (i.e., just steps 1-3 from my previous comment).

**Comment by demizer** [comment]
Sounds good to me. I'll try to get to it this weekend. :+1:
