### ISSUE TITLE
support for integer (non-string) keys in maps

### ISSUE THREAD

**Issue by Namek** [getty-zig/getty#38]
I couldn't decide whether this should be 1 ticket or 2. But my first impression was that serialization generally works and then it turned out I can't move forward because the deserialization doesn't. The latter even requires more than just implementing custom blocks, as mentioned in #37.

# Serialization

```zig
pub fn main() void {
    const Test = struct {
        some_map: std.AutoHashMap(c_int, c_int),
    };
    var obj: Test = .{
        .some_map = std.AutoHashMap(c_int, c_int).init(std.heap.page_allocator),
    };
    _ = obj.some_map.put(3, 123) catch unreachable;
    var serialized = json.toPrettySlice(gpa.allocator(), obj) catch unreachable;
    std.debug.print("{s}", .{serialized});
}
```

This prints:
```json
{
  "some_map": {
    3: 123
  }
}
```
However, the key `3` is invalid because JSON format only allows key names to be strings. The result is supposed to be:
```json
{
  "some_map": {
    "3": 123
  }
}
```

# Deserialization

However, for deserialization of the same struct, like this:
``zig
var deserialized = json.fromSlice(std.heap.page_allocator, @TypeOf(obj), "{\"some_map\": {\"3\": 123}}") catch unreachable;
std.debug.print("{any}", .{deserialized});
```
we get an error:
```
W:\dev\definitive_dialoguer\.gyro\concepts-ibokuri-github.com-05c73681\pkg\src\lib.zig:75:21: error: concept `StringKey` was not satisfied (expected key type to be `[]const u8`)
            else => @compileError(base ++ extra),
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
W:\dev\definitive_dialoguer\.gyro\concepts-ibokuri-github.com-05c73681\pkg\src\lib.zig:48:57: note: called from here
                for (results) |result| if (!result) fail(concept, msg);
                                                    ~~~~^~~~~~~~~~~~~~
W:\dev\definitive_dialoguer\.gyro\json-getty-zig-github.com-5753d08c\pkg\src\de\deserializer.zig:326:91: note: called from here
            comptime concepts.Concept("StringKey", "expected key type to be `[]const u8`")(.{
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

It is because `MapAccess.nextKeySeed` has this restriction:

```zig
comptime concepts.Concept("StringKey", "expected key type to be `[]const u8`")(.{
    concepts.traits.isSame(@TypeOf(seed).Value, []const u8),
});
```

As I mentioned in #37 I can't get through this error by implementing a custom deserialization block.

**Comment by ibokuri** [comment]
https://github.com/getty-zig/json/issues/27
